name = "MassPropsApp"
uuid = "e52a921d-2efc-494f-933a-2e86d44deae8"
version = "1.0.0-DEV"
authors = ["James Steven Jenkins <sjenkins@studioj.us> and contributors"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MassProps = "5839b151-e113-4d24-b6fd-5f05bf67e06c"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
RollupTree = "04c01c7a-6a3c-48fe-9315-f55725a63c92"

[compat]
ArgParse = "1.2.0"
CSV = "0.10.16"
DataFrames = "1.8.1"
Graphs = "1.13.4"
MetaGraphsNext = "0.8.0"
julia = "1.10.10"

[apps.rollup-mass-props]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
